### ISSUE TITLE
why 'mvn fabric8:deploy' was removed from init.sh?

### ISSUE THREAD

**Issue by rafaeltuelho** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#12]
It appears the use of Fabric 8 maven plugin was removed/comment from init.sh script.

Without this step the profiles will pick the artifacts from user's local repo `~/.m2`. As the artifact version of projects remains the same (`1.0`). As the artifacts are not using the `SNAPSHOT` qualifier the profiles will get a stale version that was built for `Fuse 6.1` (previous version of this Demo). 

This is not a problem if you are building this demo for the first time in your local machine. I think you should use the fabric8:deploy to upload a fresh version of artifacts to the Fuse internal maven repo. Another thing is to change the artifact versions or use the `SNAPSHOT` qualifier. Thus you avoid Fuse pick a stale artifact version from your local repo (`~/.m2`).

**Comment by weimeilin79** [comment]
Fixed.!
