### ISSUE TITLE
javax.jms.JMSException after starting the fuse micro containers/services

### ISSUE THREAD

**Issue by npatel2012** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#15]
Hi @eschabell @weimeilin79 

Was anybody able to test this successfully end to end? 

My initial steps went well but as soon as I started micro containers/services via Fuse management console I get the following error in the individual container log:

>> Could not refresh JMS Connection for destination 'booking' - retrying in 5000 ms. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused 

These were sequence of steps which I followed:
1. Run init.sh after copying products into install folder
2. Start BPMS server in another terminal window
3. Start Fuse server in seperate terminal window
4. Connect via FMC
5. Start container "bookingflightcon"... connect to the container and see above ERROR in logs

Has anything changed since last time? 

Kind Regards,
Niraj

**Comment by eschabell** [comment]
Running locally on my machine works for me.

**Comment by npatel2012** [comment]
Still not working for me..... Now I followed EXACTLY the following steps: 

1. Stopped all other running processes on my machine (just to avoid port conflicts if any) 

2. run init.sh.... no errors seen

3. Start BPMS

4. Build & deploy bpm project via business-central UI.... Deploys properly

5. Start Fuse and it starts properly... no containers except "root" is started:

>> JBossFuse:karaf@root> container-list 
>> [id]                [version]  [type]  [connected]  [profiles]                             [provision status]
>> root*               1.0        karaf   yes          fabric                                 success           
>>                                                    fabric-ensemble-0000-1                                   
>>                                                    jboss-fuse-full                                          
>>  bookingflightcon  1.0        karaf   no           demo-travelagency-bookingservice       stopped           
>>  bookinhotelgcon   1.0        karaf   no           demo-travelagency-hotelbookingservice  stopped           
>>  promoflightcon    1.0        karaf   no           demo-travelagency-promotionflight      stopped           
>>  promohotelcon     1.0        karaf   no           demo-travelagency-promotionhotel       stopped           
>>  wsflightcon       1.0        karaf   no           demo-travelagency-webendpoint          stopped           
>>  wshotelcon        1.0        karaf   no           demo-travelagency-hotelwsendpoint      stopped           

6. Now starting "bookingflightcon" container via FMC... The container seems to come up properly and from FMC looks like the following:

![screenshot from 2015-10-20 16-34-27](https://cloud.githubusercontent.com/assets/1553438/10612392/83e6fdb4-7748-11e5-8fc1-79fb3f63a20e.png)


7. Now when I connect to this container and view at logs it shows the following error:

![screenshot from 2015-10-20 16-36-04](https://cloud.githubusercontent.com/assets/1553438/10612492/f46eb810-7748-11e5-90de-81bf164a458c.png)


I am using the following software versions:
>> java -version
>> openjdk version "1.8.0_60"
>> OpenJDK Runtime Environment (build 1.8.0_60-b27)
>> OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)


>> mvn -version
>> Apache Maven 3.2.3


Any other pointers/help please? I am aiming to get this demo up and running on our internal EMEA Demo Central environment where SAs and others can start spinning up their own dedicated VMs from template and start using this demo.


Regards,
Niraj

**Comment by eschabell** [comment]
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

$ mvn -v
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T16:58:10-04:00)
Maven home: /Users/erics/java/apache-maven-3
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"

1. init.sh (watching lots of maven deps from Fuse download during install, be sure no failures!)
     - also ensure settings.xml from maven has admin / admin login set as outlined readme.
2. start bpm suite: ./target/jboss-eap-6.4/bin/standalone.sh
3. login and deploy bpm suite project.
4. start fuse: ./target/jboss-fuse-6.2.0.redhat-133/bin/fuse
5. login to hawtio, only root container is green (started)
6. start each container:

![screen shot 2015-10-20 at 2 55 39 pm](https://cloud.githubusercontent.com/assets/437001/10617859/b06d97d4-773a-11e5-9263-2f2b1a61ef85.png)


![screen shot 2015-10-20 at 2 56 19 pm](https://cloud.githubusercontent.com/assets/437001/10617868/c2a4b73e-773a-11e5-8fdb-1c9b444f52d6.png)


![screen shot 2015-10-20 at 2 56 59 pm](https://cloud.githubusercontent.com/assets/437001/10617874/d918f39a-773a-11e5-8c43-3ae26b11aa60.png)

Done.

**Comment by eschabell** [comment]
Assigned to Christina as it seems you have issues with Fuse containers.... maybe she has seen this before...

**Comment by weimeilin79** [comment]
It looks like your port 61616 was used or locked by some other processes, so the message broker had to changed it's port to something else. So you need to manually find out what port was assigned to your broker and change the port in the code

**Comment by npatel2012** [comment]
Hello @weimeilin79 

After debugging a bit I can see that the problem lies in between the following steps in init.sh:

#### Step 1. Command "sh $FUSE_SERVER_BIN/start" 

This starts the Fuse server which in turn starts Apache ActiveMQ and listens on 61616... Look at the log snippet below

>> 12:45:03,384 | INFO  | pool-14-thread-1 | TransportServerThreadSupport     | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Listening for connections at: **tcp://localhost.localdomain:61616**
>> 12:45:03,385 | INFO  | pool-14-thread-1 | TransportConnector               | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Connector openwire started
>> 12:45:03,385 | INFO  | pool-14-thread-1 | BrokerService                    | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Apache ActiveMQ 5.11.0.redhat-620133 (amq, ID:dhcp-1-99.fab.redhat.com-50996-1445427903190-0:1) started
>> 12:45:03,485 | INFO  | pool-14-thread-1 | ActiveMQServiceFactory           | 196 - io.fabric8.mq.mq-fabric - 1.2.0.redhat-133 | **Broker amq has started.**



#### Step 2. Command: sh $FUSE_SERVER_BIN/client -r 3 -d 10 -u admin -p admin 'fabric:create --resolver manualip --manual-ip 127.0.0.1 ' 

This command apparently brings down the previously up AMQ and starts a new instance of AMQ listening on 61617 this time

>> 2015-10-21 12:48:36,472 | INFO  | pool-14-thread-1 | BrokerService                    | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Apache ActiveMQ 5.11.0.redhat-620133 (amq, ID:dhcp-1-99.fab.redhat.com-50996-1445427903190-0:1) uptime 3 minutes
>> 2015-10-21 12:48:36,472 | INFO  | pool-14-thread-1 | BrokerService                    | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | **Apache ActiveMQ 5.11.0.redhat-620133 (amq, ID:dhcp-1-99.fab.redhat.com-50996-1445427903190-0:1) is shutdown**
>> 2015-10-21 12:48:36,809 | INFO  | pool-33-thread-1 | TransportServerThreadSupport     | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Listening for connections at: **tcp://dhcp-1-99.fab.redhat.com:61617**
>> 2015-10-21 12:48:36,809 | INFO  | pool-33-thread-1 | TransportConnector               | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | Connector openwire started
>> 2015-10-21 12:48:36,809 | INFO  | pool-33-thread-1 | BrokerService                    | 184 - org.apache.activemq.activemq-osgi - 5.11.0.redhat-620133 | **Apache ActiveMQ 5.11.0.redhat-620133 (root, ID:dhcp-1-99.fab.redhat.com-50996-1445427903190-0:2) started**
>> 2015-10-21 12:48:36,816 | INFO  | pool-33-thread-1 | ActiveMQServiceFactory           | 196 - io.fabric8.mq.mq-fabric - 1.2.0.redhat-133 | **Broker root has started.**

I wonder how this is working for you all? This behavior should be the same for everybody trying to setup this demo... Are you sure that your containers have no **javax.jms.JMSException** ERRORS when they come up?

I will now try and change 61616 ports in fuse projects to 61617 and see whether the issue still remains.


Kind Regards,
Niraj

**Comment by weimeilin79** [comment]
Are you using Red Hat Linux? I've seen this happen once on Fedora, so that's why I know your port was reset. They say this problem will be fixe on 6.2.1. I can't really do anything here. Because it's the process of Fabric creation. Currently testing 6.2.1 ER3, looks fine, but it was never a problem on my laptop.

**Comment by npatel2012** [comment]
Thanks for the info Christina... I am using Fedora 22 ATM - may be the port is not closed properly (or in a timely manner) when the next AMQ instance comes up.... 

My final aim here is to host it on RHEL7 and convert it into a template for others to use.... I may come back to you with more questions while i host it on separate VM - thanks for your continued support on this.

**Comment by npatel2012** [comment]
I will test the same on RHEL 7 (on a VM) and let you know how it goes... I will open a new case if i need anything.

**Comment by billmeyer** [comment]
I'm having the same exact problem as npatel2012 above.  A start of a clean installation of Fuse shows activemq listening on 61616.  When the fabric gets created, the port moves to 61617.  From there, all other configuration that is dependent on port 61616 being the activemq port is broken.

I'm running on stock RHEL 7.1 and JDK 8.

As a work around, I shutdown Fuse after creating the fabric, grep -r for 61617:

[jboss-fuse-6.2.0.redhat-133]$ grep -r 61617 *
data/cache/bundle7/data/config/io/fabric8/mq/fabric/server/3e4d1fe1-7a39-4dc8-a5a6-b9a639667ba7.config:bindPort="61617"

and manually edit the file to change the port number back to 61616.  Start Fuse and continue with the installation.

**Comment by eschabell** [comment]
Reopening issue for Christina to look at Bills setup for same issues mentioned above...

**Comment by eschabell** [comment]
Bill Meyer found this:

"I watched the fabric creation process on RHEL, and its not that it doesn’t shutdown properly because it does actually shutdown.  I think its more whatever is waiting for it to shutdown doesn’t wait long enough and starts the new karaf instance while the other is still shutting down and which causes it to grab the next port available.

To get around this, I found it easier to change all the port numbers before running init.sh in anticipation of the condition so that the init.sh script could run fully:

--------------------------------
#!/bin/bash

for file in projects/fuseparent/bookingservice/src/main/fabric8/test.txt \
	projects/fuseparent/bookingservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml \
	projects/fuseparent/hotelbookingservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml \
	projects/fuseparent/hotelwebendpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml \
	projects/fuseparent/promotionflights/src/main/resources/OSGI-INF/blueprint/blueprint.xml \
	projects/fuseparent/promotionhotel/src/main/resources/OSGI-INF/blueprint/blueprint.xml \
	projects/fuseparent/webendpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
do
	echo "File: $file"
	sed -i "s/61616/61617/" ${file}
done
-----------------------------

Otherwise, I’d have to hack apart the init.sh script to wait after the fabric create."

**Comment by weimeilin79** [comment]
Fix the problem by creating a standalone broker with broker on port 61618. This will hopefully bypass the root broker problem when creating fabric.

**Comment by eschabell** [comment]
Go ahead and merge it.
