### ISSUE TITLE
Setup failing again - Failed to get the session

### ISSUE THREAD

**Issue by npatel2012** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#16]
Hello,

The setup of Fuse fails when i run init.sh script on a fresh "Red Hat Enterprise Linux Server release 7.0" server... The install fails when following command tries to create fabric:

> sh $FUSE_SERVER_BIN/client -r 3 -d 10 -u admin -p admin 'fabric:create --resolver manualip --manual-ip 127.0.0.1 '

Following is the console output I see when I issue ./init.sh command:

```javascript
 JBoss Fuse installer running now...
 - enabling demo accounts logins in users.properties file...

  - enable camel counter in console in jmx.acl.whitelist.cfg  ...

  - enable camel counter in console in jmx.acl.whitelist.properties  ...

  - making sure 'FUSE' for server is executable...

  - Start up Fuse in the background

  - Create Fabric in Fuse

Logging in as admin
retrying (attempt 1) ...
retrying (attempt 2) ...
retrying (attempt 3) ...
Failed to get the session.
  - Testing fabric,retry when not ready
Failed to get the session.
Failed to get the session.
Failed to get the session.
Failed to get the session.
Failed to get the session.
Failed to get the session.
ERROR, while creating Fabric, please check your Network settings.
Start compile and deploy 3 travel agency camel demo project to fuse
```

Really frustrating to see setup failing again. I suspect that the fuse "start" command doesn't start fuse properly in background OR takes a long time to come up before next command is issued.

Will try and debug this further when I have more time.

Regards,
Niraj

**Comment by weimeilin79** [comment]
Any updates on this?

**Comment by npatel2012** [comment]
Hi,

I tried to manually run/start Fuse scripts from init.sh and am getting the following error while creating fabric:

> ERROR | pool-3-thread-3  | HawtioPlugin                     | 262 - io.hawt.hawtio-redhat-fuse-branding - 1.4.0.redhat-133 | Failed to register plugin: 
javax.management.InstanceNotFoundException: hawtio:type=plugin,name=hawtio-redhat-fuse-branding

Googling this took me to the following reported bugs :(

> https://issues.jboss.org/browse/ENTESB-3431 

Any work arounds or recommendations to automate this setup?


Regards,
Niraj

**Comment by npatel2012** [comment]
ok.... now I tried doing the Fuse setup steps entirely manually and still get the above ERROR... Additionally, when i go ahead with the setup ignoring the error then i bump into the following issue with few containers:

> Could not refresh JMS Connection for destination 'hotelbooking' - retrying in 5000 ms. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused 

The list seems never ending... Is there any way I could automate these steps (even workarounds should be fine for now)? Unfortunately manual setup wont be an option when making this demo available on EMEA Demo Central OR any other similar env where IP allocation is done dynamically.


Regards,
Niraj

**Comment by eschabell** [comment]
Has been fixed.
