### ISSUE TITLE
java.lang.NoClassDefFoundError: org/h2/mvstore/db/TransactionStore$1

### ISSUE THREAD

**Issue by npatel2012** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#20]
Hi Christina,

I was doing a fresh install and it (setup + 1 simple test) worked for the first time... Then I stopped the fuse instances (with all microservices) and restarted them all again. The subsequent test failed with following error in promoflightcon container:

> Failed delivery for (MessageId: queue_requestflight_ID_localhost-59447-1457449807738-1_2_3_1_1 on ExchangeId: ID-localhost-50265-1457450777041-1-1). Exhausted after delivery attempt: 1 caught: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (General error: "java.lang.NoClassDefFoundError: org/h2/mvstore/db/TransactionStore$1" [50000-181])

> Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[promtionFlightRout] [promtionFlightRout] [activemq://queue:requestflight                                                ] [        87]
[promtionFlightRout] [log4              ] [log                                                                           ] [         4]
[promtionFlightRout] [unmarshal2        ] [unmarshal[org.apache.camel.model.dataformat.JsonDataFormat@3307cc21]          ] [        11]
[promtionFlightRout] [setHeader5        ] [setHeader[requestDeparture]                                                   ] [         7]
[promtionFlightRout] [setHeader6        ] [setHeader[requestDestination]                                                 ] [         1]
[promtionFlightRout] [setHeader7        ] [setHeader[requestDepartureDate]                                               ] [         1]
[promtionFlightRout] [setHeader8        ] [setHeader[requestArrivalDate]                                                 ] [         0]
[promtionFlightRout] [log5              ] [log                                                                           ] [         1]
[promtionFlightRout] [setBody2          ] [setBody[simple{SELECT * from avaliableflights where departure='${header.reques] [         3]
[promtionFlightRout] [to2               ] [jdbc:dataSourceTravelAgency                                                   ] [        55]

> Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-localhost-50265-1457450777041-1-1
	ExchangePattern     InOut
	Headers             {Accept=*/*, breadcrumbId=ID-localhost-60814-1457449807442-0-1, Cache-Control=no-cache, CamelAcceptContentType=*/*, CamelHttpCharacterEncoding=UTF-8, CamelHttpMethod=POST, CamelHttpPath=/, CamelHttpUri=/cxf/acme-flight-service-2.0/, CamelRedelivered=false, CamelRedeliveryCounter=0, connection=keep-alive, Content-Type=text/xml; charset=UTF-8, Host=localhost:8182, JMSCorrelationID=Camel-ID-localhost-60814-1457449807442-0-5, JMSDeliveryMode=2, JMSDestination=queue://requestflight, JMSExpiration=1457450958696, JMSMessageID=ID:localhost-59447-1457449807738-1:2:3:1:1, JMSPriority=4, JMSRedelivered=false, JMSReplyTo=temp-queue://ID:localhost-59447-1457449807738-1:2:1, JMSTimestamp=1457450938696, JMSType=null, JMSXGroupID=null, JMSXUserID=null, operationName=listAvailablePlanes, operationNamespace=http://service.soap.jboss.com/AcmeDemo/, Pragma=no-cache, requestArrivalDate=2015-02-01, requestDeparture=London, requestDepartureDate=2015-02-10, requestDestination=Edinburgh, User-Agent=Apache CXF 2.7.14.redhat-1}
	BodyType            String
	Body                SELECT * from avaliableflights where departure='London' and destination='Edinburgh'
]

> Stacktrace
> ---------------------------------------------------------------------------------------------------------------------------------------

> 
["org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (General error: \"java.lang.NoClassDefFoundError: org/h2/mvstore/db/TransactionStore$1\" [50000-181])","\tat org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.camel.component.jdbc.JdbcProducer.processingSqlBySettingAutoCommit(JdbcProducer.java:78)[119:org.apache.camel.camel-jdbc:2.15.1.redhat-620133][org.apache.camel:camel-jdbc:2.15.1.redhat-620133]","\tat org.apache.camel.component.jdbc.JdbcProducer.process(JdbcProducer.java:65)[119:org.apache.camel.camel-jdbc:2.15.1.redhat-620133][org.apache.camel:camel-jdbc:2.15.1.redhat-620133]","\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:129)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:118)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:80)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)[117:org.apache.camel.camel-core:2.15.1.redhat-620133][org.apache.camel:camel-core:2.15.1.redhat-620133 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2]","\tat org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103)[120:org.apache.camel.camel-jms:2.15.1.redhat-620133][org.apache.camel:camel-jms:2.15.1.redhat-620133]","\tat org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990)[165:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1][org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-jms:3.2.12.RELEASE_1]","\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_91]","\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_91]","\tat java.lang.Thread.run(Thread.java:745)[:1.7.0_91]","Caused by: org.h2.jdbc.JdbcSQLException: General error: \"java.lang.NoClassDefFoundError: org/h2/mvstore/db/TransactionStore$1\" [50000-181]\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:345)\n\tat org.h2.message.DbException.get(DbException.java:168)\n\tat org.h2.message.DbException.convert(DbException.java:291)\n\tat org.h2.server.TcpServerThread.sendError(TcpServerThread.java:221)\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:161)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.NoClassDefFoundError: org/h2/mvstore/db/TransactionStore$1\n\tat org.h2.mvstore.db.TransactionStore.getChanges(TransactionStore.java:510)\n\tat org.h2.mvstore.db.TransactionStore$Transaction.getChanges(TransactionStore.java:799)\n\tat org.h2.engine.Session.rollbackTo(Session.java:606)\n\tat org.h2.command.Command.executeUpdate(Command.java:278)\n\tat org.h2.server.TcpServerThread.closeSession(TcpServerThread.java:177)\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:281)\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:159)\n\t... 1 more\n","\tat org.h2.engine.SessionRemote.done(SessionRemote.java:622)[181:org.h2:1.4.181][]","\tat org.h2.engine.SessionRemote.close(SessionRemote.java:568)[181:org.h2:1.4.181][]","\tat org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:384)[181:org.h2:1.4.181][]","\tat org.apache.commons.dbcp.DelegatingConnection.close(DelegatingConnection.java:247)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.PoolableConnection.reallyClose(PoolableConnection.java:122)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.PoolableConnectionFactory.destroyObject(PoolableConnectionFactory.java:628)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1562)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\tat org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)[123:org.apache.commons.dbcp:1.4.0][commons-dbcp:commons-dbcp:1.4]","\t... 26 more"]

Any idea why just a restart would have caused this?

Regards,
Niraj

**Comment by eschabell** [comment]
Fixed long ago.
