### ISSUE TITLE
The war is not generated in the init.sh

### ISSUE THREAD

**Issue by xiwu** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#3]
pls check the line 167, here acme-flight-service-1.0.war and acme-hotel-service-1.0.war are not generated.

mvn clean install -f $PRJ_DIR/pom.xml
cp -r $PRJ_DIR/acme-demo-flight-service/target/acme-flight-service-1.0.war $SERVER_DIR
cp -r $PRJ_DIR/acme-demo-hotel-service/target/acme-hotel-service-1.0.war $SERVER_DIR

**Comment by npatel2012** [comment]
you can safely ignore this as these Web Service applications are replaced with JBoss Fuse Web Services.

Regards,
Niraj

**Comment by xiwu** [comment]
thanks, great to know that.
