### ISSUE TITLE
init.sh gets stuck in Fuse installation step

### ISSUE THREAD

**Issue by rafaeltuelho** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#7]
I'm getting the following error during init.sh 

```
Installing JBoss FUSE 6.1.0

  - enabling demo accounts logins in users.properties file...

  - making sure 'FUSE' for server is executable...

  - Start up Fuse in the background

  - Create Fabric in Fuse

Logging in as admin
Logging in as admin
retrying (attempt 1) ...
retrying (attempt 2) ...
retrying (attempt 3) ...
Failed to get the session.
Testing fabric,retry when not ready
Failed to get the session.
Failed to get the session.
Failed to get the session.
...
```

the script gets stuck in this step. It appears an issue during Fuse fabric creation (`fabric:create`) step.

I'm trying to setup this demo in a RHEL 7 box with OpenJDK 7.

**Comment by rafaeltuelho** [comment]
It seams to be an issue with `fabric:create` command. I changed that command to the following variation:
in `init.sh` at line `216`
```
client -r 3 -d 10 -u admin -p admin 'fabric:create --resolver manualip --manual-ip 127.0.0.1 --wait-for-provisioning'
```
 and it worked fine!

**Comment by weimeilin79** [comment]
depends on how zookeeper get your IP or hostname. I would rather keep creating fabric simple, and will not assign IPs in my script

**Comment by rafaeltuelho** [comment]
Ok!
The option for assign the `localhost`  IP addr is just to avoid issues when your machine changes the IP dynamically (eg: when you connect to a VPN or change you WiFi connection). As described in this note from Fuse documentation:

> It is recommended that you assign a static IP address to the machine that hosts a Fabric server and that you specify this port explicitly using the --resolver and --manual-ip options when you create the fabric. For simple tests and demonstrations, you can specify the loopback address, 127.0.0.1 (as here).
> - https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2/html/Getting_Started/ESBGettingStarted-Fabric.html#ESBGettingStarted-Fabric-Create

For demo/LAB purposes I like to use the localhost IP addr for Fabric containers. It's just for convenience :-)

**Comment by weimeilin79** [comment]
I changed my mind! Thanks for the reminder, I think I'll make the manual IP setup to the init.sh. Since it's potentially is problem! Thanks! :)
